## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
   datasource:
     url: jdbc:mysql://localhost:3306/api_dbv1
     username: root
     password: 123456
   jpa:
     properties:
       hibernate:
         dialect: org.hibernate.dialect.MySQL5InnoDBDialect
     hibernate:
       ddl-auto: create-drop

jwt:
  secret: 12365testsecret